name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    paths-ignore:
      - '*.md'
      - '*.yml'
      - '.github/workflows/**'
    tags:
      - '!**'
  pull_request:
    branches:
      - "*"
    tags:
      - '!**'

jobs:
  build_linux:
    name: Linux x64 build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup CMake
        uses: lukka/get-cmake@latest
      - name: Build box2d-jni
        run: ./gradlew :box2d-jni-natives-linux:buildNativeLibLinux :box2d-jni:build
        working-directory: box2d-jni/

      - name: Upload native lib artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-libs
          path: |
            box2d-jni/box2d-jni/build/libs/*.jar
            box2d-jni/box2d-jni-natives-linux/build/libs/*.jar
          compression-level: 0

  build_linux_arm64:
    name: Linux arm64 build
    runs-on: ubuntu-22.04-arm

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup CMake
        uses: lukka/get-cmake@latest
      - name: Disable Android build
        run: git apply .github/disable_android.patch
      - name: Build box2d-jni
        run: ./gradlew :box2d-jni-natives-linux-arm64:buildNativeLibLinuxArm64 :box2d-jni-natives-linux-arm64:build :box2d-jni:build
        working-directory: box2d-jni/

      - name: Upload native lib artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-libs-arm64
          path: |
            box2d-jni/box2d-jni-natives-linux-arm64/build/libs/*.jar
          compression-level: 0

  build_windows:
    name: Windows build
    runs-on: windows-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup CMake
        uses: lukka/get-cmake@latest
      - name: Build box2d-jni
        run: ./gradlew :box2d-jni-natives-windows:buildNativeLibWindows :box2d-jni-natives-windows-arm64:buildNativeLibWindowsArm64 :box2d-jni:build
        working-directory: box2d-jni/

      - name: Upload native lib artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-libs
          path: |
            box2d-jni/box2d-jni/build/libs/*.jar
            box2d-jni/box2d-jni-natives-windows/build/libs/*.jar
            box2d-jni/box2d-jni-natives-windows-arm64/build/libs/*.jar
          compression-level: 0

  build_macos:
    name: macOS build (and Android)
    runs-on: macos-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install coreutils
        run: brew install coreutils
      - name: Setup CMake
        uses: lukka/get-cmake@latest
      - name: Build box2d-jni
        run: ./gradlew :box2d-jni-natives-macos-arm64:buildNativeLibMacosArm64 :box2d-jni-natives-macos:buildNativeLibMacos build
        working-directory: box2d-jni/

      - name: Upload MacOS lib artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-libs
          path: |
            box2d-jni/box2d-jni/build/libs/*.jar
            box2d-jni/box2d-jni-natives-macos/build/libs/*.jar
            box2d-jni/box2d-jni-natives-macos-arm64/build/libs/*.jar
          compression-level: 0

  build_wasm:
    name: wasm build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Build Docker Environment
        run: sudo docker compose up
        working-directory: box2d-wasm/
      - name: Build Box2D wasm
        working-directory: box2d-wasm/
        run: |
          sudo docker compose run --rm builder ./generate_release.sh
          sudo docker compose run --rm builder ./make.sh

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm-libs
          path: box2d-wasm/dist